// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Event struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	Slug        string         `json:"slug"`
	Status      string         `json:"status"`
	Date        string         `json:"date"`
	Venue       *VenueInfo     `json:"venue"`
	Inventory   *InventoryInfo `json:"inventory"`
	BannerURL   string         `json:"bannerUrl"`
	CreatedAt   string         `json:"createdAt"`
}

type InventoryInfo struct {
	TotalSlots     int32 `json:"totalSlots"`
	AvailableSlots int32 `json:"availableSlots"`
}

type InventoryInfoInput struct {
	TotalSlots     int32 `json:"totalSlots"`
	AvailableSlots int32 `json:"availableSlots"`
}

type Mutation struct {
}

type NewEvent struct {
	Title       string              `json:"title"`
	Description string              `json:"description"`
	Slug        string              `json:"slug"`
	Status      string              `json:"status"`
	Date        string              `json:"date"`
	Venue       *VenueInfoInput     `json:"venue"`
	Inventory   *InventoryInfoInput `json:"inventory"`
	BannerURL   string              `json:"bannerUrl"`
}

type Query struct {
}

type VenueInfo struct {
	Name    string `json:"name"`
	Address string `json:"address"`
}

type VenueInfoInput struct {
	Name    string `json:"name"`
	Address string `json:"address"`
}
